/*

SURF is a C program to generate and analyse instantaneous liquid interfaces.
Copyright 2015 Frank Uhlig (uhlig.frank@gmail.com)

This file is part of SURF.

SURF is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SURF is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with SURF.  If not, see <http://www.gnu.org/licenses/>.
*/

void assign_atom_parameters( char * kind, char * symdex, atom_t * atom);
void assign_acceptable_bond_lengths( real ** bondlengths );
void copy_atom(atom_t * anew, atom_t * aold);
void guess_acceptable_bond_lengths( real ** bondlengths );

typedef enum ptable_e
{
    ATOM_H=1,
    ATOM_HE,
    ATOM_LI,
    ATOM_BE,
    ATOM_B,
    ATOM_C,
    ATOM_N,
    ATOM_O,
    ATOM_F,
    ATOM_NE,
    ATOM_NA,
    ATOM_MG,
    ATOM_AL,
    ATOM_SI,
    ATOM_P,
    ATOM_S,
    ATOM_CL,
    ATOM_AR,
    ATOM_K,
    ATOM_CA,
    ATOM_SC,
    ATOM_TI,
    ATOM_V,
    ATOM_CR,
    ATOM_MN,
    ATOM_FE,
    ATOM_CO,
    ATOM_NI,
    ATOM_CU,
    ATOM_ZN,
    ATOM_GA,
    ATOM_GE,
    ATOM_AS,
    ATOM_SE,
    ATOM_BR,
    ATOM_KR,
    ATOM_RB,
    ATOM_SR,
    ATOM_Y,
    ATOM_ZR,
    ATOM_NB,
    ATOM_MO,
    ATOM_TC,
    ATOM_RU,
    ATOM_RH,
    ATOM_PD,
    ATOM_AG,
    ATOM_CD,
    ATOM_IN,
    ATOM_SN,
    ATOM_SB,
    ATOM_TE,
    ATOM_I,
    ATOM_XE,
    ATOM_CS,
    ATOM_BA,
    ATOM_LA,
    ATOM_CE,
    ATOM_PR,
    ATOM_ND,
    ATOM_PM,
    ATOM_SM,
    ATOM_EU,
    ATOM_GD,
    ATOM_TB,
    ATOM_DY,
    ATOM_HO,
    ATOM_ER,
    ATOM_TM,
    ATOM_YB,
    ATOM_LU,
    ATOM_HF,
    ATOM_TA,
    ATOM_W,
    ATOM_RE,
    ATOM_OS,
    ATOM_IR,
    ATOM_PT,
    ATOM_AU,
    ATOM_HG,
    ATOM_TL,
    ATOM_PB,
    ATOM_BI,
    ATOM_PO,
    ATOM_AT,
    ATOM_RN,
    ATOM_FR,
    ATOM_RA,
    ATOM_AC,
    ATOM_TH,
    ATOM_PA,
    ATOM_U,
    ATOM_NP,
    ATOM_PU,
    ATOM_AM,
    ATOM_CM,
    ATOM_BK,
    ATOM_CF,
    ATOM_ES,
    ATOM_FM,
    ATOM_MD,
    ATOM_NO,
    ATOM_LR,
    ATOM_RF,
    ATOM_DB,
    ATOM_SG,
    ATOM_BH,
    ATOM_HS,
    ATOM_MT,
    ATOM_DS,
    ATOM_RG,
    ATOM_CN,
    ATOM_UUT,
    ATOM_FL,
    ATOM_UUP,
    ATOM_LV,
    ATOM_UUS,
    ATOM_UUO,
    ATOM_DUMM,
    ATOM_WANN,
    LAST_ATOM,
} ptable_t;
